# For more info about this file, check the documentation at http://goreleaser.com
version: 2
release:
  github:
    owner: nirdosh17/cfn-teardown
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - ldflags:
    - -s -w -X "github.com/nirdosh17/cfn-teardown/cmd.Version={{ .Tag }}"
    env:
      - CGO_ENABLED=0
    binary: cfn-teardown
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
