# For more info about this file, check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - ldflags:
    - -X "github.com/nirdosh17/cfn-teardown/cmd.Version={{ .Tag }}"
    env:
      - CGO_ENABLED=0
    binary: cfn-teardown
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
